### Dean,Reviews His Calendar. Looks up for active sessions

GET {{u}}/calendars


### Set Timeslots for every day

POST {{u}}/timeslots
Content-Type: application/json

{
  "startTime": "07:20",
  "endTime": "07:40",
  "available": true,
  "eventId": "b5e6f45e-38ba-4d51-847c-aacf2f7d37d1"
}


### Dean Gets His Host Events
GET {{u}}/events

### Create event
# @name event
POST {{u}}/events
Content-Type: application/json

{
  "title": "Catchup: 20m",
  "duration": 20,
  "description":"Daily catchup call"
}


@eventId={{event.response.body.id}}

### Dean Signin
POST {{u}}/auth/signin
Content-Type: application/x-www-form-urlencoded

email=superdean@gmail.com&password=Hiro123@


###

POST {{u}}/auth/signup
Content-Type: application/x-www-form-urlencoded

email=superdean@gmail.com&password=Hiro123@
