### Dean,Reviews His Calendar. Looks up for active sessions

GET {{u}}/calendars


### Set Timeslots for every day

POST {{u}}/timeslots
Content-Type: application/json

{
  "startTime": "07:20",
  "endTime": "07:40",
  "available": true,
  "eventId": "{{deanEventId}}"
}


### Dean Gets His Host Events
GET {{u}}/events

### Create event
# @name event
POST {{u}}/events
Content-Type: application/json

{
  "title": "New Catchup- new Dean",
  "duration": 20,
  "description":"Working Days catchup call"
}

> {%
 eventID = response.body.id;
 if (eventID){
   client.global.set("deanEventId", response.body.id);
 }
 client.assert(eventID, "event created")
%}

### Dean Signin
POST {{u}}/auth/signin
Content-Type: application/x-www-form-urlencoded

email=superdean@gmail.com&password=Hiro123@


###

POST {{u}}/auth/signup
Content-Type: application/x-www-form-urlencoded

email=superdean@gmail.com&password=Hiro123@
