
GET {{u}}/events/ac726346-f28b-4d7e-a6b3-a1b4f594485d
Accept: application/json

###

GET {{u}}/events
Accept: application/json

###

POST {{u}}/events
Content-Type: application/json

{
 "title": "Catchup: 20m",
  "duration": 20,
  "description":"Daily catchup call"
}

###

OPTIONS {{u}}

### Enable Cors

PATCH {{u}}/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiaGlyb0BnbWFpbC5jb20iLCJpYXQiOjE2ODg5Njk3NzQsImV4cCI6MTY4ODk3MzM3NH0.wiYwslhhjB9hZBeTnmArTXybNmVhr4IEtaPp7Bs2A5Q

{
  "firstName": "Tadashi",
  "lastName": "Hamada"
}

###
GET {{u}}/users/me
Accept: application/json

###
POST {{u}}/auth/signin
Content-Type: application/x-www-form-urlencoded

email=laciferin@gmail.com&password=Hiro*2412412###@##P

###
POST {{u}}/auth/signup
Content-Type: application/x-www-form-urlencoded

email=laciferin@gmail.com&password=Hiro*2412412###@##P

###

GET {{u}}/health
Accept: application/json

###
GET {{u}}
Accept: application/json

###

