###  Student Reviews His Calendar

GET {{u}}/calendars

### Schedule a timeslot for future

POST {{u}}/calendars
Content-Type: application/json

{
  "timeSlotId": "dea96dd3-575e-4408-af76-236ef12d9ead",
  "eventId": "976b4c94-e4b1-4917-a156-7f6e90294b0d",
  "date": "2023-07-22"
}

### Gets all the events

GET {{u}}/events


### Student Signin
POST {{u}}/auth/signin
Content-Type: application/x-www-form-urlencoded

email=hirostudent@gmail.com&password=Hiro*2412412###@##P


### Student Signup
POST {{u}}/auth/signup
Content-Type: application/x-www-form-urlencoded

email=hirostudent@gmail.com&password=Hiro*2412412###@##P


