/*
  Warnings:

  - You are about to alter the column `id` on the `users` table. The data in that column will be cast from `Int` to `Int`. This cast may fail. Please make sure the data in the column can be cast.

*/
-- CreateTable
CREATE TABLE "events" (
    "id" STRING NOT NULL,
    "title" STRING NOT NULL,
    "description" STRING,
    "hostId" INT4 NOT NULL,
    "duration" INT4 NOT NULL,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "timeslots" (
    "id" STRING NOT NULL,
    "eventId" STRING NOT NULL,
    "startTime" TIMETZ NOT NULL,
    "endTime" TIMETZ NOT NULL,
    "available" BOOL NOT NULL DEFAULT true,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "timeslots_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "calendars" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "timeSlotId" STRING NOT NULL,
    "guestId" INT4 NOT NULL,
    "date" DATE NOT NULL,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "calendars_pkey" PRIMARY KEY ("id")
);

-- RedefineTables
CREATE TABLE "_prisma_new_users" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "email" STRING NOT NULL,
    "hash" STRING NOT NULL,
    "firstName" STRING,
    "lastName" STRING,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);
DROP INDEX "users_email_key";
INSERT INTO "_prisma_new_users" ("createdAt","email","firstName","hash","id","lastName","updatedAt") SELECT "createdAt","email","firstName","hash","id","lastName","updatedAt" FROM "users";
DROP TABLE "users" CASCADE;
ALTER TABLE "_prisma_new_users" RENAME TO "users";
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "events_hostId_title_duration_key" ON "events"("hostId", "title", "duration");

-- CreateIndex
CREATE UNIQUE INDEX "timeslots_eventId_startTime_endTime_key" ON "timeslots"("eventId", "startTime", "endTime");

-- CreateIndex
CREATE UNIQUE INDEX "calendars_timeSlotId_guestId_date_key" ON "calendars"("timeSlotId", "guestId", "date");

-- AddForeignKey
ALTER TABLE "events" ADD CONSTRAINT "events_hostId_fkey" FOREIGN KEY ("hostId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "timeslots" ADD CONSTRAINT "timeslots_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "calendars" ADD CONSTRAINT "calendars_timeSlotId_fkey" FOREIGN KEY ("timeSlotId") REFERENCES "timeslots"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "calendars" ADD CONSTRAINT "calendars_guestId_fkey" FOREIGN KEY ("guestId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
