### Dean SignsUp
POST {{u}}/auth/signup
Content-Type: application/x-www-form-urlencoded

email=superdean@gmail.com&password=Hiro123@

### Dean Signin
POST {{u}}/auth/signin
Content-Type: application/x-www-form-urlencoded

email=superdean@gmail.com&password=Hiro123@

### Get Your Profile
GET {{u}}/users/me

### Create event
POST {{u}}/events
Content-Type: application/json

{
  "title": "New Catchup-{{$random.uuid}}",
  "duration": 20,
  "description": "Working Days catchup call"
}

> {%
  eventID = response.body.id;
  if (eventID) {
    client.global.set("deanEventId", response.body.id);
  }
  client.assert(eventID, "event created")
%}

### Dean Gets His Host Events
GET {{u}}/events

> {%
  d = new Date()
  d.setHours(d.getHours() + 2);
  const hours = String(d.getHours()).padStart(2, '0');
  const minutes = String(d.getMinutes()).padStart(2, '0');
  slot = `${hours}:${minutes}`;
  client.log(slot)
  client.global.set("genTimeSlot", slot)

%}


### Set Timeslots for every day

POST {{u}}/timeslots
Content-Type: application/json


{
  "startTime": "{{genTimeSlot}}",
  "endTime": "",
  "available": true,
  "eventId": "{{deanEventId}}"
}

### Dean,Reviews His Calendar. Looks up for active sessions

GET {{u}}/calendars

